// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StokTakipSistemi.Models.DB
{
    public partial class Stok
    {
        public int? Id { get; set; }
        public string MalzemeAdi { get; set; }
        public int? StokAdedi { get; set; }
        public decimal? BirimFiyat { get; set; }
    }
}