// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace StokTakipSistemi.Models.DB
{
    public partial class StokTakipSistemiContext : DbContext
    {
        public StokTakipSistemiContext()
        {
        }

        public StokTakipSistemiContext(DbContextOptions<StokTakipSistemiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Stok> Stok { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=StokTakipSistemi;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Stok>(entity =>
            {
                entity.Property(e => e.BirimFiyat).HasColumnType("money");

                entity.Property(e => e.MalzemeAdi)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}